// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sxgl.EntityFramework.Core;

#nullable disable

namespace sxgl.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20260116084050_v1.0.3")]
    partial class v103
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sxgl.Core.RBAC.Entitys.Auth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Auth1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Auth1");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auth1 = "system,user",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Auth1 = "system,user",
                            Role = "Jwc"
                        },
                        new
                        {
                            Id = 3,
                            Auth1 = "user",
                            Role = "Teacher"
                        },
                        new
                        {
                            Id = 4,
                            Auth1 = "user",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("sxgl.Core.RBAC.Entitys.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("UserName");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Password = "7c4a8d09ca3762af61e59520943dc26494f8941b",
                            Role = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("sxgl.Core.RBAC.Entitys.Xyb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dm")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("xyb");
                });
#pragma warning restore 612, 618
        }
    }
}
